import type { Diagram } from "./FlowDiagram";

/* Hand-placed on the 720×450 canvas FlowDiagram draws on. */

export const gitopsCluster: Diagram = {
  title: "GitOps on a Talos Linux cluster",
  groups: [{ x: 290, y: 100, w: 410, h: 250, label: "Talos Linux · Kubernetes" }],
  nodes: [
    {
      id: "dev",
      x: 80,
      y: 345,
      w: 110,
      label: "Developer",
      sub: "git push",
      color: "#94a3b8",
      info: "Every change starts as a commit — nothing is applied to the cluster by hand.",
    },
    {
      id: "git",
      x: 80,
      y: 225,
      w: 110,
      label: "Git repo",
      sub: "Kustomize",
      color: "#F05032",
      info: "The single source of truth: Kustomize bases and overlays describe every workload.",
    },
    {
      id: "argo",
      x: 220,
      y: 225,
      w: 100,
      label: "Argo CD",
      sub: "GitOps sync",
      color: "#EF7B4D",
      info: "Watches the repo and continuously reconciles the cluster to match it, flagging drift.",
    },
    {
      id: "mastodon",
      x: 360,
      y: 170,
      w: 112,
      label: "Mastodon",
      sub: "social app",
      color: "#6364FF",
      info: "A Mastodon instance, deployed and upgraded through Git like everything else in the cluster.",
    },
    {
      id: "webui",
      x: 360,
      y: 290,
      w: 112,
      label: "Open WebUI",
      sub: "LLM chat UI",
      color: "#d4d4d8",
      info: "A self-hosted chat front end for language models, deployed the same GitOps way.",
    },
    {
      id: "prom",
      x: 505,
      y: 170,
      w: 112,
      label: "Prometheus",
      sub: "metrics",
      color: "#E6522C",
      info: "Scrapes metrics from nodes, pods and apps for alerting and capacity tracking.",
    },
    {
      id: "loki",
      x: 505,
      y: 290,
      w: 112,
      label: "Loki",
      sub: "logs",
      color: "#F5B301",
      info: "Aggregates container logs so they can be queried right next to the metrics.",
    },
    {
      id: "grafana",
      x: 638,
      y: 230,
      w: 100,
      label: "Grafana",
      sub: "dashboards",
      color: "#F46800",
      info: "One pane of glass over Prometheus and Loki: dashboards for the cluster and every app.",
    },
  ],
  edges: [
    { from: "dev", to: "git", label: "push" },
    { from: "git", to: "argo", label: "pull" },
    { from: "argo", to: "mastodon" },
    { from: "argo", to: "webui" },
    { from: "mastodon", to: "prom" },
    { from: "webui", to: "loki" },
    { from: "prom", to: "grafana" },
    { from: "loki", to: "grafana" },
  ],
};

export const maritimeMonitoring: Diagram = {
  title: "Coverage telemetry, ship to dashboard",
  groups: [
    { x: 20, y: 150, w: 150, h: 150, label: "On board" },
    { x: 182, y: 80, w: 520, h: 320, label: "Docker stack" },
  ],
  nodes: [
    {
      id: "pi",
      x: 95,
      y: 235,
      w: 120,
      label: "Pi probe",
      sub: "mobile · Wi-Fi",
      color: "#C51A4A",
      info: "A Raspberry Pi on the vessel measures mobile and Wi-Fi coverage as the ship sails.",
    },
    {
      id: "mqtt",
      x: 250,
      y: 235,
      w: 100,
      label: "MQTT",
      sub: "telemetry",
      color: "#a855f7",
      info: "Lightweight publish/subscribe transport that copes with the patchy links you get at sea.",
    },
    {
      id: "telegraf",
      x: 380,
      y: 235,
      w: 104,
      label: "Telegraf",
      sub: "ingest",
      color: "#F59E0B",
      info: "Subscribes to the MQTT topics and writes every reading into the time-series database.",
    },
    {
      id: "influx",
      x: 510,
      y: 235,
      w: 108,
      label: "InfluxDB",
      sub: "time series",
      color: "#22ADF6",
      info: "Stores every measurement with its timestamp, ready for analysis over time.",
    },
    {
      id: "grafana",
      x: 638,
      y: 140,
      w: 100,
      label: "Grafana",
      sub: "analysis",
      color: "#F46800",
      info: "Dashboards for digging into signal quality over time and per vessel.",
    },
    {
      id: "flask",
      x: 638,
      y: 245,
      w: 100,
      label: "Flask API",
      sub: "REST",
      color: "#e5e7eb",
      info: "A Python API that serves device status and measurements to the web front end.",
    },
    {
      id: "react",
      x: 638,
      y: 345,
      w: 100,
      label: "React UI",
      sub: "fleet view",
      color: "#61DAFB",
      info: "The dashboard in the screenshot: every probe in the fleet, live status first.",
    },
  ],
  edges: [
    { from: "pi", to: "mqtt", label: "publish" },
    { from: "mqtt", to: "telegraf" },
    { from: "telegraf", to: "influx" },
    { from: "influx", to: "grafana" },
    { from: "influx", to: "flask" },
    { from: "flask", to: "react" },
  ],
};
